### ISSUE TITLE
Request Enhanced feature: Can you please add cubit test, widget test and unit test on the clean architecture folder?

### ISSUE THREAD

**Issue by apptechxonia** [SinaSys/flutter_go_rest_app#1]

**Comment by lohanisuraj** [comment]
Hope you provide the test of this architecture. i will be very glad.

**Comment by SinaSys** [comment]
Hi @apptechxonia and @lohanisuraj 👋

Unfortunately, I have no plans for this because it requires time and effort. Maybe in the future.

**Comment by lohanisuraj** [comment]
@SinaSys, Thanks for you reply. Hope to see your effort on test cases in near future.
