### ISSUE TITLE
What should I do if the classes in the data/model/ folder are not the ones that need to be displayed on the screen?

### ISSUE THREAD

**Issue by yxm9264** [SinaSys/flutter_go_rest_app#5]
For example, when I retrieve a user from an API, I store the data using a User class.
class User {
  final int? id;
  final String name;
}
However, if I need to make other API requests, such as getting the user's role, I would use a Role class to store that data.
class Role {
  final int? roleId;
  final String roleName;
}
Finally, I would return a UserVo class (which is typically done in Java) to the screen.
class UserVo {
  final int? id;
  final String name;
  final int? roleId;
  final String roleName;
}
Since the same class is used in the bloc, screen, and repository, I'm not sure how to make the necessary changes. 
What is the usual approach for this? Also, I'm using #7 - MVVM Version (Bloc). 
I look forward to your reply.
Thank you.

**Comment by SinaSys** [comment]
I believe your problem is similar to [this ](https://github.com/SinaSys/flutter_go_rest_app/issues/2)one. You can check out [this ](https://github.com/SinaSys/flutter_go_rest_app/issues/2)thread, which relates to the Cubit clean version, but the same approach can be applied to the MVVM version too.

**Comment by yxm9264** [comment]
Thank you, and I hope you can add it to your code in the future. Hahaha~
